### PR TITLE
Clean up setup.py

### PR DESCRIPTION
**Pull request by rassouly**
Remove requires clause, add setuptools to setup_requires and specify
python 3.5 as the minimum version.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
The failure is not related to your changes, but  I will wait to fix it before merging (if you want to give it a try @rassouly feel free to do so).

**Comment by MatthieuDartiailh** [comment]
@rassouly can you please rebase on latest master to fix Travis.

**Comment by rassouly** [comment]
I messed up with git a little bit but it should be good now.

**Comment by MatthieuDartiailh** [comment]
Looks good thanks.

**Pull request merged**
